# Generated by Toolkit-Py[v0.18.3] Generator. Created at 2022-05-09 13:45:54.761203.

dep:
	pip install -r requirements.txt
	pip install -r requirements-dev.txt

tag:
	git tag v$(APP_VERSION)
	git push origin v$(APP_VERSION)

clean:
	-rm -r .pytest_cache

# ------------- Run with Uvicorn ------------------------------

.PHONY: run

run: ## run App on uvicorn server
	uvicorn github_trending_migrator.http:app --host 0.0.0.0 --port 12351 --reload


# ------------- Test/Lint  ------------------------------------

.PHONY: format test

format:
	pip install -U black && black .

test: ## run tests quickly with the default Python
	pytest -v -s tests
	rm -r .pytest_cache


# ------------  Docker  -----------------------------------

.PHONY: docker-build docker-run docker-clean

DOCKER_IMAGE = github-trending-api

docker-build: ## build docker image from Dockerfile
	docker build -t $(DOCKER_IMAGE) .

docker-run: ## run API docker container
	docker run -p 12351:12351 $(DOCKER_IMAGE)

docker-clean: ## remove docker image
	docker rmi -f $(DOCKER_IMAGE)
